# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-02 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('idUsuario', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('idJuego', models.CharField(choices=[('1', 'JUEGO 1'), ('2', 'JUEGO 2')], max_length=1)),
                ('puntuacion', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField(verbose_name='Fecha Jugado')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('clave', models.CharField(max_length=20)),
                ('grado', models.IntegerField(default=1)),
            ],
        ),
    ]
