# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-02 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Historial',
            new_name='Record',
        ),
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
